# Generate the FFmpeg build description from source text only.
# CMake-script port of the former Python tool, so regeneration needs
# nothing beyond the VS C++ workload:  cmake -P tools/gen_ffmpeg_build.cmake
#
# Reads third_party/ffmpeg-src (configure for the dependency graph,
# Makefiles for object lists) and emits the config headers, component
# list sources, and cmake/ffmpeg_sources.txt. FFmpeg's configure is
# never executed.
cmake_minimum_required(VERSION 3.24)

get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(FF "${ROOT}/third_party/ffmpeg-src")
# For upgrades/feature changes that add files, run against a full tree
# first, then re-vendor:  cmake -P tools/gen_ffmpeg_build.cmake <tree>
if(CMAKE_ARGV3)
  get_filename_component(FF "${CMAKE_ARGV3}" ABSOLUTE)
endif()
set(OUT "${ROOT}/third_party/ffmpeg-config")
set(FFMPEG_VERSION "n8.1.2")
set(LIBS libavutil libavcodec libavformat libswresample libswscale)
set(ARCH_DIRS x86 aarch64 arm riscv loongarch ppc mips wasm neon e2k avr32 bfin sh4 sparc)

# ---------------------------------------------------------------- selection
set(DECODERS h264 hevc mpeg2video mpeg4 msmpeg4v3 vp8 vp9
    aac mp3 ac3 eac3 flac vorbis opus
    pcm_s16le pcm_s24le pcm_s32le pcm_f32le
    subrip srt ass ssa movtext pgssub dvdsub)
set(PARSERS h264 hevc mpegvideo mpeg4video mpegaudio aac ac3 flac vorbis opus vp8 vp9)
set(DEMUXERS mov matroska avi srt ass)
set(MUXERS "")
set(ENCODERS "")
set(PROTOCOLS file)
set(BSFS null)
# Both D3D11 hwaccel families per codec: the engine negotiates AV_PIX_FMT_D3D11
# (the *_d3d11va2 hwaccels), but libavcodec/Makefile gates the shared
# implementation objects (dxva2_h264.o, ...) under the old-API
# CONFIG_*_D3D11VA_HWACCEL flags only, so both must be on.
set(HWACCELS h264_d3d11va h264_d3d11va2 hevc_d3d11va hevc_d3d11va2
    mpeg2_d3d11va mpeg2_d3d11va2 vp9_d3d11va vp9_d3d11va2)
set(EXTRA_CONFIG avcodec avformat avutil swresample swscale
    static decoders demuxers parsers protocols bsfs
    safe_bitstream_reader swscale_alpha)
set(HAVE_FLAGS W32THREADS THREADS)

set(KINDS decoder encoder parser demuxer muxer protocol bsf hwaccel)
set(KINDLIST_decoder "${DECODERS}")
set(KINDLIST_encoder "${ENCODERS}")
set(KINDLIST_parser "${PARSERS}")
set(KINDLIST_demuxer "${DEMUXERS}")
set(KINDLIST_muxer "${MUXERS}")
set(KINDLIST_protocol "${PROTOCOLS}")
set(KINDLIST_bsf "${BSFS}")
set(KINDLIST_hwaccel "${HWACCELS}")

# ------------------------------------------------------------ configure text
file(READ "${FF}/configure" CONF)
string(REPLACE ";" " " CONF "${CONF}")
set(CONF "\n${CONF}")
foreach(q "\"" "'")
  string(REGEX MATCHALL "\n[a-zA-Z0-9_]+_(select|deps)=${q}[^${q}\n]*${q}" ms "${CONF}")
  foreach(m ${ms})
    string(REGEX REPLACE "^\n([a-zA-Z0-9_]+)_(select|deps)=${q}([^${q}]*)${q}$"
           "\\1|\\3" kv "${m}")
    string(REPLACE "|" ";" kv "${kv}")
    list(GET kv 0 name)
    list(LENGTH kv n)
    if(n GREATER 1)
      list(GET kv 1 deps)
      string(REGEX MATCHALL "[^ \t]+" deps "${deps}")
      list(APPEND "GRAPH_${name}" ${deps})
    endif()
  endforeach()
endforeach()

# ------------------------------------------------------------- declarations
function(collect_decl file kind)
  file(READ "${file}" t)
  string(REPLACE ";" "|" t "${t}")  # matches must not contain list separators
  string(REGEX MATCHALL "ff_[a-z0-9_]+_${kind}\\|" ms "${t}")
  set(names "")
  foreach(m ${ms})
    string(REGEX REPLACE "^ff_(.+)_${kind}\\|$" "\\1" n "${m}")
    list(APPEND names "${n}")
  endforeach()
  list(REMOVE_DUPLICATES names)
  set("DECLS_${kind}" "${names}" PARENT_SCOPE)
endfunction()

collect_decl("${FF}/libavcodec/allcodecs.c" decoder)
collect_decl("${FF}/libavcodec/allcodecs.c" encoder)
collect_decl("${FF}/libavcodec/parsers.c" parser)
collect_decl("${FF}/libavformat/allformats.c" demuxer)
collect_decl("${FF}/libavformat/allformats.c" muxer)
collect_decl("${FF}/libavformat/protocols.c" protocol)
collect_decl("${FF}/libavcodec/bitstream_filters.c" bsf)
collect_decl("${FF}/libavcodec/hwaccels.h" hwaccel)

set(bad "")
foreach(kind ${KINDS})
  foreach(n ${KINDLIST_${kind}})
    if(NOT "${n}" IN_LIST "DECLS_${kind}")
      list(APPEND bad "${n}_${kind}")
    endif()
  endforeach()
endforeach()
if(bad)
  message(FATAL_ERROR "unknown components: ${bad}")
endif()

# ------------------------------------------------------------------ closure
set(queue "")
foreach(kind ${KINDS})
  foreach(n ${KINDLIST_${kind}})
    list(APPEND queue "${n}_${kind}")
  endforeach()
endforeach()
list(APPEND queue ${EXTRA_CONFIG})

set(enabled "")
while(queue)
  list(POP_BACK queue n)
  if(DEFINED "EN_${n}")
    continue()
  endif()
  set("EN_${n}" 1)
  list(APPEND enabled "${n}")
  if(DEFINED "GRAPH_${n}")
    list(APPEND queue ${GRAPH_${n}})
  endif()
endwhile()

set(COMP_SUFFIX_RE "_(decoder|encoder|parser|demuxer|muxer|protocol|bsf|hwaccel|filter|indev|outdev)$")
set(components "")
set(subsystems "")
foreach(n ${enabled})
  if(n MATCHES "${COMP_SUFFIX_RE}")
    list(APPEND components "${n}")
  else()
    list(APPEND subsystems "${n}")
  endif()
endforeach()
list(SORT components)
list(SORT subsystems)

# -------------------------------------------------- referenced macro scan
# FFmpeg uses config macros as C expressions, so every referenced
# HAVE_/CONFIG_/ARCH_ macro must be defined. Token-boundary matching is
# emulated by splitting on non-word characters.
set(referenced "")
foreach(top ${LIBS} compat)
  file(GLOB_RECURSE files "${FF}/${top}/*.c" "${FF}/${top}/*.h")
  foreach(f ${files})
    file(READ "${f}" t)
    string(REGEX REPLACE "[^A-Za-z0-9_]" ";;" t ";;${t};;")
    string(REGEX MATCHALL ";(HAVE|CONFIG|ARCH)_[A-Z0-9_]+;" ms "${t}")
    foreach(m ${ms})
      string(REPLACE ";" "" m "${m}")
      if(NOT DEFINED "REF_${m}")
        set("REF_${m}" 1)
        list(APPEND referenced "${m}")
      endif()
    endforeach()
  endforeach()
endforeach()
list(REMOVE_ITEM referenced "HAVE_AV_CONFIG_H")

# CPUEXT(flags, LSX) token-pastes HAVE_##LSX(_EXTERNAL/...): derive those
# names from paste sites since they never appear literally.
foreach(top ${LIBS} compat)
  file(GLOB_RECURSE files "${FF}/${top}/*.h")
  foreach(f ${files})
    file(READ "${f}" t)
    string(REGEX MATCHALL "CPUEXT(_SUFFIX)?\\([ \t]*flags[ \t]*,[ \t]*[A-Za-z0-9_]+[ \t]*\\)" ms "${t}")
    foreach(m ${ms})
      string(REGEX REPLACE ".*,[ \t]*([A-Za-z0-9_]+)[ \t]*\\)$" "\\1" name "${m}")
      string(TOUPPER "${name}" base)
      foreach(suffix "" "_EXTERNAL" "_INLINE" "_FAST" "_SLOW")
        if(NOT DEFINED "REF_HAVE_${base}${suffix}")
          set("REF_HAVE_${base}${suffix}" 1)
          list(APPEND referenced "HAVE_${base}${suffix}")
        endif()
      endforeach()
    endforeach()
  endforeach()
endforeach()

set(COMP_SUFFIX_RE_U "_(DECODER|ENCODER|PARSER|DEMUXER|MUXER|PROTOCOL|BSF|HWACCEL|FILTER|INDEV|OUTDEV)$")
set(ref_components "")
set(ref_other "")
foreach(m ${referenced})
  if(m MATCHES "^CONFIG_" AND m MATCHES "${COMP_SUFFIX_RE_U}")
    list(APPEND ref_components "${m}")
  else()
    list(APPEND ref_other "${m}")
  endif()
endforeach()

# ------------------------------------------------------------------ sources
function(flag_on negate kind flag outvar)
  if(kind STREQUAL "HAVE")
    if("${flag}" IN_LIST HAVE_FLAGS)
      set(res 1)
    else()
      set(res 0)
    endif()
  else()
    string(TOLOWER "${flag}" lf)
    if(DEFINED "EN_${lf}")
      set(res 1)
    else()
      set(res 0)
    endif()
  endif()
  if(negate STREQUAL "!")
    if(res)
      set(res 0)
    else()
      set(res 1)
    endif()
  endif()
  set("${outvar}" "${res}" PARENT_SCOPE)
endfunction()

set(sources "")
set(missing "")
foreach(lib ${LIBS})
  set(makefiles "${FF}/${lib}/Makefile")
  file(GLOB subs "${FF}/${lib}/*/Makefile")
  list(SORT subs)
  foreach(s ${subs})
    get_filename_component(dir "${s}" DIRECTORY)
    get_filename_component(dirname "${dir}" NAME)
    if(NOT "${dirname}" IN_LIST ARCH_DIRS)
      list(APPEND makefiles "${s}")
    endif()
  endforeach()

  foreach(mk ${makefiles})
    file(READ "${mk}" t)
    string(REPLACE ";" " " t "${t}")
    string(REGEX REPLACE "\\\\\n" " " t "${t}")
    string(REPLACE "\n" ";" lines "${t}")
    foreach(line ${lines})
      if(NOT line MATCHES "^(OBJS|STLIBOBJS)(-\\$\\((!?)(CONFIG|HAVE)_([A-Z0-9_]+)\\))?[ \t]*[+:]?=[ \t]*(.*)$")
        continue()
      endif()
      set(negate "${CMAKE_MATCH_3}")
      set(fkind "${CMAKE_MATCH_4}")
      set(flag "${CMAKE_MATCH_5}")
      set(rhs "${CMAKE_MATCH_6}")
      if(NOT flag STREQUAL "")
        flag_on("${negate}" "${fkind}" "${flag}" res)
        if(NOT res)
          continue()
        endif()
      endif()
      # expand $(if $(!CONFIG_X), a b) / $(if $(CONFIG_X), a b)
      while(rhs MATCHES "\\$\\(if \\$\\((!?)(CONFIG|HAVE)_([A-Z0-9_]+)\\),([^)]*)\\)")
        set(whole "${CMAKE_MATCH_0}")
        flag_on("${CMAKE_MATCH_1}" "${CMAKE_MATCH_2}" "${CMAKE_MATCH_3}" on)
        if(res)
          set(repl "${CMAKE_MATCH_4}")
        else()
          set(repl "")
        endif()
        string(REPLACE "${whole}" "${repl}" rhs "${rhs}")
      endwhile()
      string(REGEX MATCHALL "[^ \t]+" toks "${rhs}")
      foreach(tok ${toks})
        if(tok MATCHES "\\$")
          message(STATUS "warn: skipping unexpanded token '${tok}' in ${mk}")
        elseif(tok MATCHES "\\.o$")
          string(REGEX REPLACE "\\.o$" ".c" c "${tok}")
          set(c "${lib}/${c}")
          if(EXISTS "${FF}/${c}")
            list(APPEND sources "${c}")
          else()
            list(APPEND missing "${lib}/${tok}")
          endif()
        endif()
      endforeach()
    endforeach()
  endforeach()
endforeach()
list(REMOVE_DUPLICATES sources)
list(SORT sources)

# --------------------------------------------------------------------- emit
file(MAKE_DIRECTORY "${OUT}" "${OUT}/libavcodec" "${OUT}/libavformat" "${OUT}/libavutil")
set(gen_note "/* Generated by tools/gen_ffmpeg_build.cmake - do not edit */\n")

set(enabled_comp_macros "")
foreach(c ${components})
  string(TOUPPER "${c}" u)
  list(APPEND enabled_comp_macros "CONFIG_${u}")
endforeach()
list(SORT enabled_comp_macros)

# every declared component must exist as a macro: sources paste names like
# CONFIG_PCM_##id##_DECODER that never appear literally
set(all_comp_macros "${ref_components}")
foreach(kind ${KINDS})
  string(TOUPPER "${kind}" ku)
  foreach(n ${DECLS_${kind}})
    string(TOUPPER "${n}" nu)
    list(APPEND all_comp_macros "CONFIG_${nu}_${ku}")
  endforeach()
endforeach()
list(REMOVE_DUPLICATES all_comp_macros)
list(REMOVE_ITEM all_comp_macros ${enabled_comp_macros})
list(SORT all_comp_macros)

set(body "${gen_note}#ifndef FFMPEG_CONFIG_COMPONENTS_H\n#define FFMPEG_CONFIG_COMPONENTS_H\n")
foreach(m ${enabled_comp_macros})
  string(APPEND body "#define ${m} 1\n")
endforeach()
string(APPEND body "/* all other declared/referenced components: off */\n")
foreach(m ${all_comp_macros})
  string(APPEND body "#ifndef ${m}\n#define ${m} 0\n#endif\n")
endforeach()
string(APPEND body "#endif\n")
file(WRITE "${OUT}/config_components.h" "${body}")

function(write_list path typ var kind names)
  set(body "${gen_note}static const ${typ} * const ${var}[] = {\n")
  foreach(n ${names})
    string(APPEND body "    &ff_${n}_${kind},\n")
  endforeach()
  string(APPEND body "    NULL };\n")
  file(WRITE "${path}" "${body}")
endfunction()

write_list("${OUT}/libavcodec/codec_list.c" FFCodec codec_list decoder "${DECODERS}")
write_list("${OUT}/libavcodec/parser_list.c" AVCodecParser parser_list parser "${PARSERS}")
write_list("${OUT}/libavcodec/bsf_list.c" FFBitStreamFilter bitstream_filters bsf "${BSFS}")
write_list("${OUT}/libavformat/demuxer_list.c" FFInputFormat demuxer_list demuxer "${DEMUXERS}")
write_list("${OUT}/libavformat/muxer_list.c" FFOutputFormat muxer_list muxer "${MUXERS}")
write_list("${OUT}/libavformat/protocol_list.c" URLProtocol url_protocols protocol "${PROTOCOLS}")

file(READ "${ROOT}/tools/config_msvc_win64.h" template)
string(REGEX MATCHALL "#define (HAVE|CONFIG|ARCH)_[A-Z0-9_]+" tdefs "${template}")
foreach(d ${tdefs})
  string(REGEX REPLACE "^#define " "" d "${d}")
  set("TDEF_${d}" 1)
endforeach()

set(subsystem_macros "")
foreach(s ${subsystems})
  string(TOUPPER "${s}" u)
  set(m "CONFIG_${u}")
  set("SUBM_${m}" 1)
  if(NOT DEFINED "TDEF_${m}")
    list(APPEND subsystem_macros "${m}")
  endif()
endforeach()
list(SORT subsystem_macros)

set(zero_fill "")
foreach(m ${ref_other})
  if(NOT DEFINED "TDEF_${m}" AND NOT DEFINED "SUBM_${m}")
    list(APPEND zero_fill "${m}")
  endif()
endforeach()
list(SORT zero_fill)

set(body "${gen_note}${template}\n/* --- subsystem flags from the configure dependency graph --- */\n")
foreach(m ${subsystem_macros})
  string(APPEND body "#define ${m} 1\n")
endforeach()
string(APPEND body "\n/* --- every other macro referenced by the tree: off --- */\n")
foreach(m ${zero_fill})
  string(APPEND body "#ifndef ${m}\n#define ${m} 0\n#endif\n")
endforeach()
string(APPEND body "#endif /* FFMPEG_CONFIG_H */\n")
file(WRITE "${OUT}/config.h" "${body}")

file(WRITE "${OUT}/libavutil/avconfig.h"
  "${gen_note}#ifndef AVUTIL_AVCONFIG_H\n#define AVUTIL_AVCONFIG_H\n#define AV_HAVE_BIGENDIAN 0\n#define AV_HAVE_FAST_UNALIGNED 1\n#endif\n")
file(WRITE "${OUT}/libavutil/ffversion.h"
  "${gen_note}#ifndef AVUTIL_FFVERSION_H\n#define AVUTIL_FFVERSION_H\n#define FFMPEG_VERSION \"${FFMPEG_VERSION}\"\n#endif\n")

set(body "# Generated by tools/gen_ffmpeg_build.cmake - do not edit\n")
foreach(s ${sources})
  string(APPEND body "${s}\n")
endforeach()
file(WRITE "${ROOT}/cmake/ffmpeg_sources.txt" "${body}")

list(LENGTH components ncomp)
list(LENGTH subsystems nsub)
list(LENGTH sources nsrc)
message(STATUS "components: ${ncomp}  subsystems: ${nsub}  sources: ${nsrc}")
if(missing)
  message(STATUS "objects with no .c (excluded): ${missing}")
endif()
