#!/usr/bin/env python3
"""Flatten the needed FFmpeg source subset into the repo as plain files.

Reads cmake/ffmpeg_sources.txt (the compiled set), walks the transitive
quoted-#include closure inside the FFmpeg tree (headers, template .c
files, tables), and copies exactly that subset - plus the build
description inputs (configure, Makefiles) and the license text - into
third_party/ffmpeg-src/. After this, the repo is fully self-contained:
no submodule, no fetch from any other git at build time.

Usage: python3 tools/vendor_ffmpeg.py <path-to-ffmpeg-tree>
(The source tree is only needed when vendoring/upgrading, never to build.)
"""

import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "third_party" / "ffmpeg-src"
LIBS = ["libavutil", "libavcodec", "libavformat", "libswresample", "libswscale"]
ARCH_DIRS = {"x86", "aarch64", "arm", "riscv", "loongarch", "ppc", "mips",
             "wasm", "neon", "e2k", "avr32", "bfin", "sh4", "sparc"}
# generated by tools/gen_ffmpeg_build.py, not part of the upstream tree
GENERATED = {"config.h", "config_components.h", "avconfig.h", "ffversion.h",
             "codec_list.c", "parser_list.c", "bsf_list.c", "demuxer_list.c",
             "muxer_list.c", "protocol_list.c", "filter_list.c",
             "indev_list.c", "outdev_list.c"}

INC_RE = re.compile(r'^\s*#\s*include\s+"([^"]+)"', re.M)


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__)
        return 1
    ff = Path(sys.argv[1]).resolve()

    roots = [
        line.strip()
        for line in (ROOT / "cmake" / "ffmpeg_sources.txt").read_text().splitlines()
        if line.strip() and not line.startswith("#")
    ]
    # build-description inputs the generator reads (kept for regeneration)
    extra = ["configure", "COPYING.LGPLv2.1", "CREDITS", "MAINTAINERS"]
    for lib in LIBS:
        extra.append(f"{lib}/Makefile")
        for sub in sorted((ff / lib).iterdir()):
            if sub.is_dir() and sub.name not in ARCH_DIRS and (sub / "Makefile").exists():
                extra.append(f"{lib}/{sub.name}/Makefile")
    for e in extra:
        if (ff / e).exists():
            roots.append(e)

    seen: set[str] = set()
    queue = list(roots)
    while queue:
        rel = queue.pop()
        if rel in seen:
            continue
        p = ff / rel
        if not p.exists():
            continue
        seen.add(rel)
        if p.suffix not in (".c", ".h", ".inc"):
            continue
        for name in INC_RE.findall(p.read_text(errors="ignore")):
            base = Path(name).name
            if base in GENERATED:
                continue
            # mirror the compiler's search: includer's dir, tree root,
            # then each lib root (superset resolution is safe: it only
            # copies a few extra same-named headers)
            cands = [str((Path(rel).parent / name)), name] + [
                f"{lib}/{name}" for lib in LIBS
            ]
            for cand in cands:
                cp = (ff / cand)
                try:
                    c = str(cp.resolve().relative_to(ff)).replace("\\", "/")
                except ValueError:
                    continue
                if cp.is_file() and c not in seen:
                    queue.append(c)

    if OUT.exists():
        shutil.rmtree(OUT)
    for rel in sorted(seen):
        src = ff / rel
        dst = OUT / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)

    commit = "unknown"
    try:
        commit = subprocess.run(
            ["git", "-C", str(ff), "rev-parse", "HEAD"],
            capture_output=True, text=True, check=True).stdout.strip()
    except Exception:
        pass
    (OUT / "PROVENANCE.txt").write_text(
        "Origin: https://git.ffmpeg.org/ffmpeg.git (mirror github.com/FFmpeg/FFmpeg)\n"
        f"Tag: n8.1.2\nCommit: {commit}\n"
        f"Files: {len(seen)} (compiled subset + transitive includes + build "
        "description inputs)\nVendored by tools/vendor_ffmpeg.py; unmodified "
        "upstream text. License: LGPL-2.1-or-later (COPYING.LGPLv2.1).\n")

    total = sum((OUT / r).stat().st_size for r in sorted(seen))
    print(f"vendored {len(seen)} files, {total / 1e6:.1f} MB -> {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
