# Flatten the needed FFmpeg source subset into the repo as plain files.
# CMake-script port of the former Python tool:
#   cmake -P tools/vendor_ffmpeg.cmake <path-to-ffmpeg-tree>
#
# Reads cmake/ffmpeg_sources.txt (the compiled set), walks the transitive
# quoted-#include closure inside the given FFmpeg tree, and copies exactly
# that subset - plus the build description inputs (configure, Makefiles)
# and the license text - into third_party/ffmpeg-src/. The source tree is
# only needed when vendoring/upgrading, never to build.
cmake_minimum_required(VERSION 3.24)

if(NOT CMAKE_ARGV3)
  message(FATAL_ERROR "usage: cmake -P tools/vendor_ffmpeg.cmake <ffmpeg-tree>")
endif()
get_filename_component(FF "${CMAKE_ARGV3}" ABSOLUTE)
get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(OUT "${ROOT}/third_party/ffmpeg-src")
set(LIBS libavutil libavcodec libavformat libswresample libswscale)
set(ARCH_DIRS x86 aarch64 arm riscv loongarch ppc mips wasm neon e2k avr32 bfin sh4 sparc)
# generated by tools/gen_ffmpeg_build.cmake, not part of the upstream tree
set(GENERATED config.h config_components.h avconfig.h ffversion.h
    codec_list.c parser_list.c bsf_list.c demuxer_list.c muxer_list.c
    protocol_list.c filter_list.c indev_list.c outdev_list.c)

file(STRINGS "${ROOT}/cmake/ffmpeg_sources.txt" roots REGEX "^[^#]")

set(extra configure COPYING.LGPLv2.1 CREDITS MAINTAINERS)
foreach(lib ${LIBS})
  list(APPEND extra "${lib}/Makefile")
  file(GLOB subs "${FF}/${lib}/*/Makefile")
  list(SORT subs)
  foreach(s ${subs})
    get_filename_component(dir "${s}" DIRECTORY)
    get_filename_component(dirname "${dir}" NAME)
    if(NOT "${dirname}" IN_LIST ARCH_DIRS)
      list(APPEND extra "${lib}/${dirname}/Makefile")
    endif()
  endforeach()
endforeach()
foreach(e ${extra})
  if(EXISTS "${FF}/${e}")
    list(APPEND roots "${e}")
  endif()
endforeach()

set(seen "")
set(queue "${roots}")
while(queue)
  list(POP_BACK queue rel)
  if(DEFINED "SEEN_${rel}")
    continue()
  endif()
  if(NOT EXISTS "${FF}/${rel}")
    continue()
  endif()
  set("SEEN_${rel}" 1)
  list(APPEND seen "${rel}")
  if(NOT rel MATCHES "\\.(c|h|inc)$")
    continue()
  endif()
  file(READ "${FF}/${rel}" t)
  string(REPLACE ";" " " t "${t}")
  set(t "\n${t}")
  string(REGEX MATCHALL "\n[ \t]*#[ \t]*include[ \t]+\"[^\"]+\"" ms "${t}")
  get_filename_component(reldir "${rel}" DIRECTORY)
  foreach(m ${ms})
    string(REGEX REPLACE ".*\"([^\"]+)\"$" "\\1" name "${m}")
    get_filename_component(base "${name}" NAME)
    if("${base}" IN_LIST GENERATED)
      continue()
    endif()
    # mirror the compiler's search: includer's dir, tree root, then each
    # lib root (superset resolution only copies a few extra headers)
    set(cands "${name}")
    if(NOT reldir STREQUAL "")
      list(PREPEND cands "${reldir}/${name}")
    endif()
    foreach(lib ${LIBS})
      list(APPEND cands "${lib}/${name}")
    endforeach()
    foreach(cand ${cands})
      get_filename_component(abs "${FF}/${cand}" ABSOLUTE)
      string(FIND "${abs}" "${FF}/" pos)
      if(NOT pos EQUAL 0)
        continue()
      endif()
      string(REPLACE "${FF}/" "" c "${abs}")
      if(EXISTS "${abs}" AND NOT IS_DIRECTORY "${abs}" AND NOT DEFINED "SEEN_${c}")
        list(APPEND queue "${c}")
      endif()
    endforeach()
  endforeach()
endwhile()

file(REMOVE_RECURSE "${OUT}")
list(SORT seen)
foreach(rel ${seen})
  get_filename_component(d "${OUT}/${rel}" DIRECTORY)
  file(MAKE_DIRECTORY "${d}")
  file(COPY_FILE "${FF}/${rel}" "${OUT}/${rel}")
endforeach()

set(commit "unknown")
execute_process(COMMAND git -C "${FF}" rev-parse HEAD
                OUTPUT_VARIABLE gitout OUTPUT_STRIP_TRAILING_WHITESPACE
                ERROR_QUIET RESULT_VARIABLE gitres)
if(gitres EQUAL 0 AND NOT gitout STREQUAL "")
  set(commit "${gitout}")
endif()
list(LENGTH seen n)
file(WRITE "${OUT}/PROVENANCE.txt"
  "Origin: https://git.ffmpeg.org/ffmpeg.git (mirror github.com/FFmpeg/FFmpeg)\n"
  "Tag: n8.1.2\nCommit: ${commit}\n"
  "Files: ${n} (compiled subset + transitive includes + build "
  "description inputs)\nVendored by tools/vendor_ffmpeg.cmake; unmodified "
  "upstream text. License: LGPL-2.1-or-later (COPYING.LGPLv2.1).\n")

message(STATUS "vendored ${n} files -> ${OUT}")
